Rnf68
diegoferques/cosmeticos pull request #37
Opened 2017-07-26 05:19 UTC by diegoferques

@garrydias , favor analisar tudo que fiz e reconsiderar a pontuação do card abaixo:

https://trello.com/c/Mm41AYrN/68-retornar-e-mail-j%C3%A1-existente-ao-tentar-cadastrar-um-e-mail-que-ja-existe-na-tabela-user

2017-07-26 05:56 UTC, KillerJV approved these changes
Aprovado.

2017-07-26 14:42 UTC, garrydias requested changes
Po, tem como mudar so aquele if que comentei? Usa uma daquelas boas praticas q eu pus la. Vlw

2017-07-26 14:42 UTC, garrydias commented on src/main/java/com/cosmeticos/service/UserService.java
> +        if(userOptional.isPresent()) {
Boa pratica:
(1) 
 a= b.isPresent();
return a;// facilita debugar


(2)
return b.isPresent();// pros mais ousados q nao curtem debugar

2017-07-26 14:42 UTC, garrydias commented on src/test/java/com/cosmeticos/controller/CustomerControllerTests.java
> +		testCreateOK();
Quando se começa a precisar fazer esse tipo de coisa dentro de um teste unitario, reaproveitar um  um metodo q ja faz o q vc precisa, isso eh sinal de que seu teste deve ir pra uma classe separada que atenda exclusivamente ao cenario que vc quer.

Nao ta errado mas testes sem tendencia à simplicidade costumam sofrer esse refactor.

2017-07-28 01:28 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/UserService.java
> +        if(userOptional.isPresent()) {
Feito

2017-07-28 03:00 UTC, garrydias approved these changes
Valeu!

2017-07-28 03:00 UTC, garrydias commented on src/main/java/com/cosmeticos/controller/CustomerController.java
> +                    responseBody.setDescription("E-mail já existente.");
Esse tipo de informacao que retornada para uma aplicacao cliente ou aplicacao frontend, eh bom colocar o texto no properties.
Mais pra frente vemos isso.

2017-07-28 03:00 UTC, merged