Rnf105
diegoferques/cosmeticos pull request #58
Opened 2017-08-20 05:16 UTC by diegoferques

O último a aprovar delete a Branch!

2017-08-20 12:55 UTC, garrydias requested changes

2017-08-20 12:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new IllegalStateException("PROIBIDO ATUALIZAR PARA O MESMO STATUS.");
Seria um bom caso pra retornar CONFLICT(409). OrderController retorna forbidden se vc lançar essa exceção. Lance OrderValidationException que o controller vai retornar 409 pro cliente. Faz sentido?

2017-08-20 12:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
O correto seria 2 então né? Se faremos a captura posteriormente, o status correto seria "Pago e não capturado", correto?

2017-08-20 12:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +						//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO AO ATUALIZAR O STATUS DO PAGAMENTO
Erros na plataforma deles como: erros 500, connection refused, timeout, service unavailable, essas coisas de infra-estrutura, o ideal seria lançarmos uma exceção nova chamada IntegrationException e capturá-la no OrderController, que por sua vez, retorna ao cliente um 502 (bad gateway).

Se for erro retornado no response deles, teríamos que tratar caso a caso. Retornar http 5xx se o problema for falha no nosso request (tipo usuario preenche td certo mas tem bug do nosso lado que acaba fazendo request errado ao superpay); ou Retornar 4xx caso o usuário esteja enviando dados errados;

2017-08-20 12:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +					log.error("Erro ao efetuar o pagamentos {}", retornoTransacaoSuperpay.get().getStatusTransacao());
Não precisa logar aqui pois o controller ja vai capturar esta exceção e logar. Se vc tbm incluir este log aqui, este erro vai gerar 2 linhas de log e vai ficar um inferno rastrear o problema no futuro. Pode apagar esta linha de log.

2017-08-20 12:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO NO PAGAMENTO NA SUPERPAY
Lançar uma checked exception nossa, que possa ser capturada pelo catch do controller e responder 502 ao client.

2017-08-20 12:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new Exception("ParseException", e);
Não é boa pratica fazer isso. Todas as exceções são filhas de Exception. Nós devemos sempre lançar exceções mais específicas, Exception é generica demais. Tem um nome pra isso que vc está fazendo aqui mas nao lembro agora.

Aqui, vc poderia: nao tratar essas exceções e incluílas na cláusula throws do metodo ou manter esses catches mas lançar uma exceção nossa.

Como esses erros, se acontecerem, são problemas no nosso codigo, eu faria o throws delas duas, pois OrderController tem um catch(Exception) que vai capturar esses erros e vai responder ao client "internal server error".

2017-08-20 12:56 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +						//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO AO ATUALIZAR O STATUS DO PAGAMENTO
Isso aqui não precisa ser alterado neste PR

2017-08-20 12:57 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO NO PAGAMENTO NA SUPERPAY
Nao precisa simplementar esse lance do 502 neste PR

2017-08-20 16:19 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
E se por algum descuido da Superpay eles o pedido for capturado tbm? Não estaria errado para o cliente, ele terá feito o pagamento com sucesso.

Acha que deveríamos tratar se veio PAGO E CAPTURADO e mandar cancelar o pagamento para, então, novamente tentar fazer o pagamento do cliente?

A configuração de CAPTURA AUTOMATICA ou MANUAL está configurada na SUPERPAY, se eles mudarem lá para AUTOMATICA, todos os pedidos aprovados virão como PAGO E CAPTURADO e não adianta cancelar e tentar novamente para vir como NÃO CAPTURADO.

E mais, se tentar fazer várias vezes o mesmo pagamento, com o mesmo valor, para o mesmo estabelecimento, geralmente as operadoras de cartão de crédito bloqueiam o cartão por segurança, ou então bloqueiam as vendas seguintes no mesmo estabelecimento.

Creio que o mais prudente seria aceitar o pagamento, internamente notificar para os desenvolvedores e responsáveis que as vendas estão vindo já CAPTURADAS para, então, entrarmos em contato com a SUPERPAY para resolver com eles.

OBS.: ESTOU ACHANDO ESSA SUPERPAY MUITO FUNDO DE QUINTAL, NOS OUTROS GATEWAYS ESSA CAPTURA AUTOMÁTICA OU MANUAL SÃO ENVIADAS POR PARÂMETROS NO MOMENTO DO REQUEST DE CRIAÇÃO DE PEDIDO DE PAGAMENTO.

2017-08-20 16:19 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
@garrydias

2017-08-20 16:21 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +						//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO AO ATUALIZAR O STATUS DO PAGAMENTO
Show, mas tem que abrir um card com essa solicitação para não esquecer, né!?

2017-08-20 16:21 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO NO PAGAMENTO NA SUPERPAY
Show, mas tem que abrir um card com essa solicitação para não esquecer, né!?

2017-08-20 16:23 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new Exception("ParseException", e);
Show, já estava com a cabeça quente de tanto ficar nisso aqui que tinha até esquecido dos catchs(Exceptions) existente em OrderControler.
Rs

2017-08-20 16:23 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +					log.error("Erro ao efetuar o pagamentos {}", retornoTransacaoSuperpay.get().getStatusTransacao());
Tinha esquecido do OrderController que faz isso!

2017-08-21 05:48 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
Isso é sério, acho que deveríamos logar um WARN pra esse caso. Eu entendo sua preocupação, mas nao sei se vale a pena ja desenvolver algo contando com a imcopetencia do parceiro. Como vc ja identificou esse problema em potencial, logar um warn ou enviar o email caso isso ocorra seria o ideal.

2017-08-21 05:58 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO NO PAGAMENTO NA SUPERPAY
Abert https://trello.com/c/SdNMw8Vk

2017-08-24 03:25 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new IllegalStateException("PROIBIDO ATUALIZAR PARA O MESMO STATUS.");
Se for pra lançar OrderValidationException, então não seria melhor já tratar isso dentro de Validation?

E mais, se lançar isso, terá que tratar qual a causa da exceção e responder corretamente, caso contrário, o responseBody para o cliente está definido manualmente como abaixo:

orderResponseBody.setDescription("Erro: Profissional não pode ter duas Orders simultaneas em andamento. - {}: " + errorCode);

2017-08-24 03:30 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new IllegalStateException("PROIBIDO ATUALIZAR PARA O MESMO STATUS.");
Mas ja trata. O controller trata OrderValidationExc.. e retorna exatamente 409.

No catch, dá pra fazer orderResponseBody.setDescription(e.getMessage()) e deixar pra escrever a mensagem no ponto onde é lançada a exceção. Fica bom assim tbm.

2017-08-24 18:05 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new IllegalStateException("PROIBIDO ATUALIZAR PARA O MESMO STATUS.");
Feito!

2017-08-24 18:10 UTC, garrydias commented
A foda agora é que este PR caducou. Ta conflitando.

Dpois ve se é facil resolver os conflitos.. Nem precisa rodar de novo TODOS os testes. Só resolver os conflitos pra poder mergearmos esta branch.

Valeu

2017-08-24 18:37 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
Mas só vou logar e não vou lançar nenhuma Exception ou algo do tipo?

2017-08-24 18:44 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
Fiz conforme segue abaixo, somente logando WARN, sem lançar exception ou fazer outra coisa:

`//VALIDAMOS SE VEIO O STATUS QUE ESPERAMOS
				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 2, POIS FAREMOS A CAPTURA POSTERIORMENTE)
				if(retornoTransacaoSuperpay.get().getStatusTransacao() == 2 ||
						retornoTransacaoSuperpay.get().getStatusTransacao() == 1) {

					//SE FOR PAGO E CAPTURADO, HOUVE UM ERRO NAS DEFINICOES DA SUPERPAY, MAS FOI FEITO O PAGAMENTO
					if (retornoTransacaoSuperpay.get().getStatusTransacao() == 1) {
						log.warn("Pedido retornou como PAGO E CAPTURADO, mas o correto seria PAGO E 'NÃO' CAPTURADO.");
					}`

2017-08-24 18:49 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +					log.error("Erro ao efetuar o pagamentos {}", retornoTransacaoSuperpay.get().getStatusTransacao());
Retirei o log.error

2017-08-24 18:53 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO NO PAGAMENTO NA SUPERPAY
Tah, mas o que faço aqui então? Nada?

2017-08-24 18:55 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
Isso mesmo.. pro usuário temos que retornar sucesso mas devemos nos alertar a esse problema.

Sabe se a inocente sabe pq está retornando "pago e capturado" logo de cara?

2017-08-24 19:03 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new Exception("ParseException", e);
Feito, coloquei no método!

2017-08-24 19:04 UTC, diegoferques commented
Como resolvo estes conflitos, pelo próprio Intellij fazendo o merge dev e depois fazendo push novamente?

2017-08-24 20:10 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//TODO - NAO SEI QUAL SERIA A MALHOR SOLUCAO QUANDO DER UM ERRO NO PAGAMENTO NA SUPERPAY
Nada

2017-08-24 20:12 UTC, garrydias commented
Faz pull de dev, volta pra sua branch, faz merge com dev, depois botao direito, git, resolve conlicts

2017-08-25 02:13 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +				//1 = Pago e Capturado | 2 = Pago e não Capturado (O CORRETO SERIA 1, POIS FAREMOS A CAPTURA POSTERIORMENTE)
Novamente?
Rs

Pq está configurado para retornar isso, acho que essa pergunta é antiga. Pois acho que já te expliquei isso.
Rs

2017-08-25 02:15 UTC, garrydias requested changes

2017-08-25 02:15 UTC, garrydias commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new OrderValidationException();
Tem que por uma mensagem na exception.

2017-08-25 02:15 UTC, garrydias commented on src/main/java/com/cosmeticos/controller/OrderController.java
> -            orderResponseBody.setDescription("Erro: Profissional não pode ter duas Orders simultaneas em andamento. - {}: " + errorCode);
Esta mensagem foi movida deveria ser movida praquele throw new OrdervalidationException sem mensam do outro comentario, nao?

2017-08-25 02:37 UTC, diegoferques commented on src/main/java/com/cosmeticos/service/OrderService.java
> +			throw new OrderValidationException();
Feito

2017-08-25 02:43 UTC, diegoferques commented on src/main/java/com/cosmeticos/controller/OrderController.java
> -            orderResponseBody.setDescription("Erro: Profissional não pode ter duas Orders simultaneas em andamento. - {}: " + errorCode);
Não entendi isso

2017-08-25 02:46 UTC, diegoferques commented on src/main/java/com/cosmeticos/controller/OrderController.java
> -            orderResponseBody.setDescription("Erro: Profissional não pode ter duas Orders simultaneas em andamento. - {}: " + errorCode);
Abrindo a exibição completa do código que coloca lado a lado as modificações, pude entender!
Rs

Retirei a mensagem setada manualmente daqui e coloquei uma outra lá onde lança a exceção.

2017-08-25 02:47 UTC, diegoferques commented on src/main/java/com/cosmeticos/controller/OrderController.java
> -            orderResponseBody.setDescription("Erro: Profissional não pode ter duas Orders simultaneas em andamento. - {}: " + errorCode);
Coloquei o que segue abaixo:

> `throw new OrderValidationException("PROIBIDO ATUALIZAR PARA O MESMO STATUS.");`

2017-08-25 02:56 UTC, garrydias approved these changes

2017-08-25 02:56 UTC, merged